

logging:
  level:
    root: info
    com:
      example:
        todo:
          req: trace
    org:
      hibernate: info


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demodb
    username: root
    password: mariadb

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB106Dialect
    show-sql: true
    hibernate:
      database: mysql
      generate-ddl: true
      ddl-auto: update